### ISSUE TITLE
2020-04-10-action1: write prose for implementation report ref to json-ld.org implementation list (Rob Sanderson)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#142]
write prose for implementation report ref to json-ld.org implementation list (Rob Sanderson) ([see details](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-04-10-json-ld#action1))

Cc: @azaroth42

**Comment by azaroth42** [comment]
@gkellogg I looked at `reports/template.haml` and thought better of trying to edit it directly.

How about the following section to be added before Instructions for submitting:

## Introduction

This implementation report covers the implementations of the JSON-LD specifications which have submitted test results. It is intended to be maintained by the JSON for Linking Data Community Group, or a JSON-LD Working Group if one is active.  The implementation report serves two purposes:

  1.  To demonstrate that there are multiple, independent implementations of the specifications. This is a prerequisite for progression of any standard to Recommendation.
  2.  To catalog the known, conforming implementations and which features each supports.

There are other JSON-LD implementations which are not listed in this report, either due to not submitting tests or by not being intended as direct implementations of the specification, but instead layering on top of such libraries.  For a broader list of implementations, please see the [JSON-LD Website](https://json-ld.org/#developers).
