### ISSUE TITLE
Proposal: Create a new `json-ld-primer` repository / note

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/json-ld-wg#17]
This would be a non-normative Group Note focused on getting developers started with the core concepts of working with JSON-LD as a syntax.

Primers abound in the W3C world (and beyond), so I believe this has precedence and it's time has come. 😁 

I'm happy to lead some of the initial authoring/editing, but I'll need help. @ajs6f also mentioned an interest.

@iherman @azaroth42 let me know how we move this toward reality. 😄

**Comment by BigBlueHat** [comment]
@davidlehn pointed me to an earlier attempt at a primer:
https://github.com/json-ld/json-ld.org/tree/master/primer/latest

Presumably we could/would pick up that work and go from there (depending on its state/updated-ness).

**Comment by iherman** [comment]
A WG can decide to publish any WG Note it wishes. So if the WG decides to go ahead, then I can set up a separate github repo and off we go...

**Comment by BigBlueHat** [comment]
@iherman do we need to put this to a vote to get a repo? or should we just continue the work on the CG copy and then move it if/when it get's a +1 to become a work item?

**Comment by ajs6f** [comment]
@BigBlueHat Are we thinking of two docs? I.e. a primer and a best practices doc? To me, those are two very different document types that should be written independently (while informing each other).

**Comment by BigBlueHat** [comment]
@ajs6f oh. Good question. I'd imagined them as a single thing. I'm open to two...but I don't want this to grow beyond our capabilities/time/interest.

**Comment by iherman** [comment]
@BigBlueHat I did not mean 'vote' in a formal sense and a resolution and stuff. We should agree in the group that we really want to do that, that is all.

Setting up a repo is a non-issue, you just have to ask me:-)

**Comment by ajs6f** [comment]
@BigBlueHat Yep, good point-- we have only so many hands. Actually, that might be one reason to split 'em up-- we could use different techniques for each. A primer (to my mind) really needs to be written very coherently and edited very carefully with a single POV. A best practices doc _could_ be "assembled" via wiki pages or the like (practice-per-page) by several people and then edited together at a later stage. 

Or that might be overcomplicating things before we even start. :grin:

**Comment by iherman** [comment]
>  I'll dig into the Primer on the CG site, and ping you when the time comes for a proper repo--unless we should start that sooner because provenance and process?

There is no process. The WG asks and I execute 😄

**Comment by azaroth42** [comment]
I agree that a best practices doc is different from a primer. They might contain similar content, but the audience and intent are different. In my experience:

* Primer: Audience is newcomers to the work. Content is written informally. Intent is pedagogical.
* Best Practice: Audience is people actively using the work. Content is written semi-formally. Intent is to document non-normative but useful recommendations for encouraging consistency.

Consider best practice docs:
* https://www.w3.org/TR/ldp-bp/
* https://www.w3.org/TR/dwbp/ 
* https://www.w3.org/TR/mobile-bp/ 
* https://www.w3.org/TR/sdw-bp/ 

And primer docs:
* https://www.w3.org/TR/prov-primer/
* https://www.w3.org/TR/rdf11-primer/
* https://www.w3.org/TR/xmlschema-0/
* https://www.w3.org/TR/tabular-data-primer/

**Comment by iherman** [comment]
This is overwritten by event, and is part of the action #49, see also https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-03-01-json-ld#action1.

Propose closing (@BigBlueHat ?)

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-04-05-json-ld#section3).

- `RESOLVED:  close #17 as started with other issues/work to follow`
<details><summary><i class="differentiate">View the transcript</i></summary>
Best Practices / Primer / Cookbook<br/>
Benjamin Young: <a href="https://github.com/w3c/json-ld-wg/issues/17">https://github.com/w3c/json-ld-wg/issues/17</a><br/>
Benjamin Young: We have a stub primer that Ivan has made<br/>
Benjamin Young: <a href="https://w3c.github.io/json-ld-bp/">https://w3c.github.io/json-ld-bp/</a><br/>
Adam Soroka: +1<br/>
Benjamin Young: and so I think we can close the meta issue<br/>
Proposed resolution: close #17 as started with other issues/work to follow (Benjamin Young)<br/>
Pierre-Antoine Champin: It says community group?<br/>
Ivan Herman: +1<br/>
Ivan Herman: Yes, that will be changed ASAP … it’s imported from the CG<br/>
Benjamin Young: +1<br/>
Pierre-Antoine Champin: +1<br/>
Rob Sanderson: +1<br/>
Harold Solbrig: +1<br/>
Rob Sanderson: +1<br/>
Simon Steyskal: +1<br/>
Jeff Mixter: +1<br/>
Adam Soroka: +1<br/>
Resolution #2: close #17 as started with other issues/work to follow<br/>
Benjamin Young: Should I close by hand?<br/>
Ivan Herman: I usually put in comments<br/>
</details>
