### ISSUE TITLE
Complete Privacy Horizontal Review

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/json-ld-wg#88]

**Comment by azaroth42** [comment]
Requested review

**Comment by azaroth42** [comment]
Questions from Privacy:

1) I don’t see a point where the described API touches the Web API.  How is this intended to be used by applications running in the browser?

2) What privacy relevant information is sent with calls to the [documentLoader](https://www.w3.org/TR/json-ld11-api/#dom-jsonldoptions-documentloader) end point?  Cookies or similar?  If so, pulled from what origin (and single or double keyed), etc?  In general more explanation of how this interacts with the browser is needed.

3) If this is intended to be implanted in browsers, have any vendors implemented it?  Generally W3C prefers at least two independent implementations of functionality before standardizing / recommending.

4) How does the contextUrl interact with other URL / origin specific privacy features in the browser (same origin policy, CORS, etc?)

**Comment by azaroth42** [comment]
Answers to submit:

1. The API is intended to be used by javascript applications running in the browser only, rather than by the browser itself. It provides structured data to the application to process and act upon, rather than performing any function or service. There isn't a model for how a data block in a web page interacts with the HTML or DOM, nor are we chartered to work on this.

2. The endpoints are only interacted with via Fetch, XHR or similar existing browser-side APIs available to page-level javascript. Thus the information sent to the endpoint is exactly the same as for any API available via HTTP. For the document loader, the expectation is that the code will perform an HTTP GET request for the document. We only describe the behavior of a conforming product once that document has been retrieved. 

3. As the specification is for use within the application layer, rather than the browser directly, there isn't an intent for browsers to implement this natively.  However, it is our understanding that Google have implemented a JSON-LD processor in Lighthouse (https://developers.google.com/web/tools/lighthouse/), which powers the Audits panel of the devtools package in Chrome. There are multiple implementations of the specification outside of browser-space, in multiple languages.

4. The context URL is simply more JSON data ... or actually meta-data, as it describes how a conforming processor should transform the instance data into the RDF data model. As such, it uses the same methods as above, and as are already implemented by browser, with the existing privacy considerations.

**Comment by azaroth42** [comment]
Response from Privacy:

> The situation seems unique. I’m not aware of many other examples of W3C specs defining interfaces / APIs that are not intended to be implemented by vendors, or even quite what the role of such a standard would be in this context.  My understanding of Web IDL is that  [“define(s) interfaces for Web APIs”][1], and so I’m kinda lost how to evaluate a web standard API that’s not meant to be implemented by web browsers. I don’t mean that as any kind of criticism, just that I’m unfamiliar with this situation and how to evaluate it.  

> Independent of the above concern though, if the API is explicitly _not_ designed to be implemented by browsers, and is supposed to be operating on data describing the relationship between data, and not between the browser’s current user, it would be good to specify that requests initiated through the API _must not_ have any user describing state (referer, cookies, origin, etc).  Would there be any conflict / problem / loss in doing so?

We need to discuss in particular the question in the second paragraph.

**Comment by azaroth42** [comment]
Discussion from early august not captured here:

> We discussed the questions in the WG and feel that you're right that the situation is a clear edge case. We have been encouraged to use WebIDL for consistency with other specifications, and even to the point of having to put in slightly spurious fields (such as that the scope is a window, because respec requires that field to be present or it raises errors!).

> In terms of the interactions, by browser or other client system, all of the interactions fall through to the existing APIs such as XMLHttpRequest and Fetch. We don't make any requirements there, and expect that the cookies and other headers that the user has allowed to be sent will be sent. For example, if the client needs to be authenticated in order to retrieve a JSON-LD context file, then the authentication information should be sent in the regular way.  So we can't say MUST NOT send any state or user tracking information, but we certainly neither require any in particular, nor have any special considerations. 

WG feels that we are in good shape with respect to privacy.

**Comment by azaroth42** [comment]
Response:

Thank you for this, and for clarifying further.  I dont have any further privacy concerns, thanks for explaining further.  I dont know if you will get concerns about the WebIDL being kinda/sorta not correct since its not really hanging off the Window interface, but thats not my department, and seems you’ve already thought through that anyway :)

Propose closing, done :)
